title: Darshika Verma
logo: /assets/img/mypic.png   
description: 
  Authorized to work in the United States
  Phone: +1 412-500-5170  
  Email: Dverma1@my.harrisburgu.edu  
  [LinkedIn](https://www.linkedin.com/in/darshika-verma/) · [GitHub](https://github.com/darshika1994)
show_downloads: true
theme: jekyll-theme-minimal


