title: Darshika Verma
logo: /assets/img/coverpic.png   
description: Authorized to work in the United States | Dverma1@my.harrisburgu.edu | 412-500-5170
show_downloads: false
theme: jekyll-theme-minimal
