title: Darshika Verma
logo: /assets/img/mypic.png   # remove this line if you don’t want the photo in the sidebar
description: |
  Authorized to work in the United States  
  Available to start immediately  
  Phone: +1 412-500-5170  
  Email: Dverma1@my.harrisburgu.edu  
  [LinkedIn](https://www.linkedin.com/in/darshika-verma/) · [GitHub](https://github.com/darshika1994)

show_downloads: true
url: "https://darshika1994.github.io/portfolio"
theme: jekyll-theme-minimal



