title: <h1 style="text-align:center; color:#1F4E79;">Darshika Verma</h1>
logo: /assets/img/mypic.png
description: Authorized to work in the United States | Available to start immediately
show_downloads: true
url: "https://darshika1994.github.io/portfolio"
theme: jekyll-theme-minimal
